services:
  as-spa-db:
    image: postgres:17
    container_name: as-spa-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: as_spa_postgres_data

networks:
  postgres-network:
    driver: bridge

# Add a script to generate init.sql before starting the container
x-generate-init: &generate-init
  command: ./generate-init.sh
  volumes:
    - .:/app
  working_dir: /app